version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php85-todo-app
    ports:
      - "8080:8080"
    volumes:
      - ./src:/var/www/html
      - ./database:/var/www/database
      - ./composer.json:/var/www/composer.json
      - ./phpunit.xml:/var/www/phpunit.xml
      - ./tests:/var/www/tests
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t /var/www/html
    environment:
      - DB_PATH=/var/www/database/todos.db
